# Generated by Django 3.1.1 on 2020-10-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200914_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-last_active', 'name', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name', 'user__username', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp', '-pk']},
        ),
        migrations.AddField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
