# Generated by Django 3.1.1 on 2020-10-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_customer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
