# Generated by Django 3.1.1 on 2020-11-04 19:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20201028_0048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='Administrator',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp', 'pk']},
        ),
    ]
